### ISSUE TITLE
CLJC Version

### ISSUE THREAD

**Issue by bowbahdoe** [timrichardt/hicgql#1]
Hi there,

We have a use case for making graphql queries on the backend. If there is no blocker, can this library be made to work as a cljc file? Copy pasting works but i'd rather not

**Comment by timrichardt** [comment]
I made it a cljc and use https://github.com/dakrone/cheshir for now. Let me know if you think there is something better.

**Comment by timrichardt** [comment]
v0.2.0 is cljc now using cheshire for JSON.
